services:
  app:
    container_name: app
    image: debian:bookworm-slim
    platform: linux/amd64
    volumes: [./zig-out/bin/mud:/usr/local/bin/mud]
    entrypoint: ["/usr/local/bin/mud"]
    ports:
      - "9862:9862"
      - "9224:9224"

  auto:
    image: crossbario/autobahn-testsuite:latest
    profiles: ["test"]
    volumes:
      - ./tools:/tools
      - ./reports:/reports
    command: ["wstest", "-m", "fuzzingclient", "-s", "/tools/fuzzingclient.json"]

  test:
    build:
      context: .
      target: pytest
    profiles: ["test"]
    command: python -m pytest
    volumes: [./pytest:/repo/pytest]

  oauthmock:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim
    volumes: [./oauth_mock.py:/app/main.py]
    command: ["/bin/sh", "-c", "pip install --quiet faker && uvicorn main:app --host 0.0.0.0 --port 80"]
    ports: ["8000:80"]
