networks:
  slow-net:
    external: true
    name: slow-net

services:
  app:
    container_name: app
    image: debian:bookworm-slim
    platform: "linux/amd64"
    volumes: [./zig-out/bin/mud:/usr/local/bin/mud]
    entrypoint: ["/usr/local/bin/mud"]
    ports:
      - "9862:9862"
      - "9224:9224"

  netem:
    build:
      context: .
      target: slow
    environment:
      NETEM_IFACE: br_slow
      NETEM_DELAY: 120ms
      NETEM_JITTER: 20ms
      NETEM_LOSS: 0.5%
      NETEM_RATE: 40mbit
    network_mode: host
    privileged: true
    profiles: ["slow"]


  test:
    build:
      context: .
      target: pytest
    profiles: ["test"]
    # depends_on: ["app"]
    command: python -m pytest
    volumes: [./pytest:/repo/pytest]
