services:
  app:
    container_name: app
    image: debian:bookworm-slim
    platform: linux/amd64
    volumes: [./zig-out/bin/mud:/usr/local/bin/mud]
    entrypoint: ["/usr/local/bin/mud"]
    ports:
      - "9862:9862"
      - "9224:9224"

  auto:
    image: crossbario/autobahn-testsuite:latest
    profiles: ["test"]
    volumes:
      - ./config:/config
      - ./reports:/reports
    command: ["wstest", "-m", "fuzzingclient", "-s", "/config/fuzzingclient.json"]

  test:
    build:
      context: .
      target: pytest
    profiles: ["test"]
    command: python -m pytest
    volumes: [./pytest:/repo/pytest]
