services:
  app:
    container_name: app
    image: debian:bookworm-slim
    platform: linux/amd64
    volumes: [./zig-out/bin/mud:/usr/local/bin/mud]
    entrypoint: ["/usr/local/bin/mud"]
    ports:
      - "9862:9862"
      - "9224:9224"

  auto:
    image: crossbario/autobahn-testsuite:latest
    profiles: ["test"]
    volumes:
      - ./tools:/tools
      - ./reports:/reports
    command: ["wstest", "-m", "fuzzingclient", "-s", "/tools/fuzzingclient.json"]

  test:
    build:
      context: .
      target: pytest
    profiles: ["test"]
    command: python -m pytest
    volumes: [./pytest:/repo/pytest]

  oauth:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim
    environment: ["CLIENT_ID=ninjamagic", "CLIENT_SECRET=secret"]
    volumes: [./pytest/oauth_provider.py:/app/main.py]
    command: ["/bin/sh", "-c", "pip install --quiet faker && uvicorn main:app --host 0.0.0.0"]
    ports: ["8000:8000"]

  oauthtest:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim
    environment:
      - CLIENT_ID=ninjamagic
      - CLIENT_SECRET=secret
    volumes: [./pytest/oauth_test.py:/app/main.py]
    command: ["/bin/sh", "-c", "pip install --quiet requests && uvicorn main:app --host 0.0.0.0"]
    ports: ["8001:8000"]
