networks:
  slow-net:
    external: true
    name: slow-net

services:
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ziguser
      POSTGRES_PASSWORD: zigpass
      POSTGRES_DB: zigdb
    volumes:
      # - ./.db:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      retries: 5

  app:
    container_name: app
    build: 
      context: .
      target: runtime
    platform: "linux/amd64"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9862:9862"
      - "9224:9224"

  netem:
    build:
      context: .
      target: slow
    environment:
      NETEM_IFACE: br_slow
      NETEM_DELAY: 120ms
      NETEM_JITTER: 20ms
      NETEM_LOSS: 0.5%
      NETEM_RATE: 40mbit
    network_mode: host
    privileged: true
    profiles: ["slow"]


  test:
    build:
      context: .
      target: pytest
    profiles: ["test"]
    # depends_on: ["app"]
    command: python -m pytest
